spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_ums
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapperLocations: classpath*:/mapper/**/*.xml
  globalConfig:
    dbConfig:
      idType: auto

server:
  port: 8000