spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_sms
    driverClassName: com.mysql.cj.jdbc.Driver
#    注册该微服务
  cloud:
    nacos:
      discovery:
        serverAddr: 127.0.0.1:8848
  application:
    name: gulimall-coupon

mybatis-plus:
  mapperLocations: classpath*:/mapper/**/*.xml
  globalConfig:
    dbConfig:
      idType: auto

#解决依赖循环
spring.main:
  allow-circular-references: true

# 设置端口
server:
  port: 7000

